---
- name: Check if user exists
  shell: /bin/false
  register: user_exists
  failed_when: false
  changed_when: False

- name: Add deployment user
  user: name={{ deploy_user }} password={{ deploy_password }} shell=/bin/bash update_password=always state=present
  when: user_exists.rc != 0

- name: Add authorized deploy keys
  action: "authorized_key user={{ deploy_user }} key=\"{{ lookup('file', item) }}\""
  with_items: '{{ ssh_public_key_files }}'

- name: Add deploy user to sudoers
  lineinfile: dest=/etc/sudoers line="{{ deploy_user }} ALL=(ALL:ALL) ALL" state=present

- name: Allow deploy user restart app server
  lineinfile: dest=/etc/sudoers line="{{ deploy_user }} ALL=NOPASSWD:/bin/systemctl restart puma.service" state=present

- name: Check if oh-my-zsh installed
  shell: '[ -d .oh-my-zsh ]'
  register: zsh_exists
  failed_when: false
  changed_when: False

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  become_method: su
  become: yes
  become_user: "{{ deploy_user }}"
  when: zsh_exists.rc != 0

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  become_method: su
  become: yes
  become_user: "{{ deploy_user }}"
  when: zsh_exists.rc != 0

- name: Switch shell to Zsh
  command: "chsh {{deploy_user}} -s /usr/bin/zsh"
  when: zsh_exists.rc != 0
