openapi: "3.0.0"
info:
  description: "API documentation"
  version: "1.0.0"
  title: "OWTB"

servers:
  - url: http://localhost:3000/api
    description: Development
paths:
  /v1/session:
    $ref: './endpoints/v1/session.yml#/collection/index'

  /v1/profile:
    $ref: './endpoints/v1/profile.yml#/collection/index'
  /v1/profile/confirm:
    $ref: './endpoints/v1/profile.yml#/collection/confirm'

components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "X-User-Token"
      in: "header"